# Generated by Django 2.0.5 on 2018-05-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='suit',
            new_name='suite',
        ),
    ]
